In [2]:
import torch
import numpy as np 

'''
initializing from data
'''




'\ninitializing from data\n'

In [3]:

data = [[1 , 2] , [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
# from np array 

np_array = np.array(data) 
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [8]:
x_rand = torch.rand_like(x_data , dtype=torch.float)
x_rand

tensor([[0.8763, 0.2873],
        [0.4119, 0.5767]])

In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")


In [11]:
tensor

tensor([[0.8908, 0.2948, 0.4605, 0.9261],
        [0.1193, 0.0011, 0.9442, 0.9766],
        [0.4407, 0.8535, 0.6211, 0.4739]])

In [13]:
torch.ones(4,4 )[: , -1] == torch.ones(4,4 )[... , -1]


tensor([True, True, True, True])

In [15]:
torch.ones(4,4 )[: , -1].shape

torch.Size([4])

In [20]:
torch.rand(4 , 4) @ torch.rand(3 , 4).T

tensor([[0.8765, 0.6078, 1.0935],
        [0.7366, 0.4849, 0.8057],
        [1.6073, 0.9051, 1.3912],
        [1.0678, 0.5569, 0.8875]])

In [21]:
torch.rand(4 , 4).matmul( torch.rand(3 , 4).T)

tensor([[1.0521, 0.6891, 0.4596],
        [0.9851, 0.9510, 0.3220],
        [1.2536, 0.9433, 0.3874],
        [1.2948, 1.0924, 0.3662]])